services:

  fogbus2-naive_formula1:
    image: cloudslab/fogbus2-naive_formula1:1.0
    build:
      context: ../../
      dockerfile: dockerFiles/NaiveFormula1/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
