services:

  fogbus2-user:
    image: cloudslab/fogbus2-user:1.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./sources:/workplace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    privileged: true
    restart: unless-stopped
    networks:
      - fogbus2
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  fogbus2:
    external: true


