services:

  fogbus2-naive_formula3:
    image: cloudslab/fogbus2-naive_formula3:1.0
    build:
      context: ../../
      dockerfile: dockerFiles/NaiveFormula3/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
