services:

  fogbus2-remote_logger:
    image: cloudslab/fogbus2-remote_logger:1.0
    build:
      context: ./
      dockerfile: ./Dockerfile
      network: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./sources:/workplace
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
    restart: unless-stopped
    ports:
      - "5000:5000"
