services:

  fogbus2-naive_formula2:
    image: cloudslab/fogbus2-naive_formula2:1.0
    build:
      context: ../../
      dockerfile: dockerFiles/NaiveFormula2/Dockerfile
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Australia/Melbourne
